force-app/main/default/objects/Product_Sourcing_Option__c/Product_Sourcing_Option__c.object-meta.xml
<CustomObject>
        <label>Product Sourcing Option</label>
    <nameField>
        <label>Sourcing Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sourcing Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Product Sourcing Option</relationshipLabel>
    <relationshipName>BU_Product_Sourcing_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Contract_Cost_Per_Vendor_Unit__c.field-meta.xml
<CustomField>
    <fullName>Contract_Cost_Per_Vendor_Unit__c</fullName>
    <description>BU-specific contracted cost per vendor unit.</description>
    <label>Contract Cost Per Vendor Unit</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Effective_From__c</fullName>
    <description>Start date for BU-specific vendor contract terms.</description>
    <label>Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Effective_To__c</fullName>
    <description>End date for BU-specific vendor contract terms.</description>
    <label>Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this BU Vendor Product is active.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Sourcing Option</relationshipLabel>
    <relationshipName>Product_Product_Sourcing_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Vendor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Sourcing Option</relationshipLabel>
    <relationshipName>Vendor_Product_Sourcing_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Vendor_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor Product available to this Business Unit.</description>
    <label>Vendor Product</label>
    <referenceTo>Vendor_Product__c</referenceTo>
    <relationshipLabel>Product Sourcing Option</relationshipLabel>
    <relationshipName>Vendor_Products_Product_Sourcing_Option</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Business_Unit_Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Vendor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Vendor_Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <label>Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Factor__c</fullName>
    <description>Snapshot of conversion factor (internal units per vendor unit).</description>
    <label>Conversion Factor</label>
    <precision>16</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Converted_Internal_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Converted_Internal_Quantity__c</fullName>
    <description>Quantity in internal base units (Vendor Quantity * Conversion Factor).</description>
    <label>Converted Internal Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Cost_Per_Vendor_Unit__c.field-meta.xml
<CustomField>
    <fullName>Cost_Per_Vendor_Unit__c</fullName>
    <description>Cost per vendor unit at the time of order (snapshot).</description>
    <label>Vendor Unit Cost</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Internal_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Internal_Quantity__c</fullName>
    <label>Internal Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Internal_UOM__c.field-meta.xml
<CustomField>
    <fullName>Internal_UOM__c</fullName>
    <label>Internal Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_of_Measure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal product associated with this line.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Product_Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Product_Sourcing_Option__c.field-meta.xml
<CustomField>
    <fullName>Product_Sourcing_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Business Unit specific Vendor Product configuration used for this line.</description>
    <label>Product Sourcing Option</label>
    <referenceTo>Product_Sourcing_Option__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Product_Sourcing_Option_PO_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <description>Parent purchase order.</description>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>PO_Purchase_Order_Lines</relationshipName>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Vendor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Vendor_Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Vendor_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor product ordered on this line.</description>
    <label>Vendor Product</label>
    <referenceTo>Vendor_Product__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Vendor_Product_Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Vendor_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Quantity__c</fullName>
    <description>Quantity in vendor units ordered on this line.</description>
    <label>Vendor Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <required>true</required>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Vendor_UOM__c.field-meta.xml
<CustomField>
    <fullName>Vendor_UOM__c</fullName>
    <label>Vendor Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_of_Measure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/Vendor_Product__c.object-meta.xml
<CustomObject>
    <label>Vendor Product</label>
    <nameField>
        <label>Vendor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Product__c/fields/Base_Cost_Per_Vendor_Unit__c.field-meta.xml
<CustomField>
    <fullName>Base_Cost_Per_Vendor_Unit__c</fullName>
    <description>Standard cost per vendor unit, before BU-specific contracts.</description>
    <label>Base Cost Per Vendor Unit</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/fields/Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Factor__c</fullName>
    <description>Number of internal base units per one vendor unit (e.g. 5 for a 5-gallon pail).</description>
    <label>Conversion Factor</label>
    <precision>16</precision>
    <scale>6</scale>
    <required>true</required>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/fields/Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Effective_From__c</fullName>
    <description>Date from which this vendor product configuration is effective.</description>
    <label>Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/fields/Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Effective_To__c</fullName>
    <description>Date until which this vendor product configuration is effective.</description>
    <label>Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether this vendor product is active.</description>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Vendor Products</relationshipLabel>
    <relationshipName>Product_Vendor_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Vendor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Products</relationshipLabel>
    <relationshipName>Vendor_Vendor_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/fields/Vendor_UOM__c.field-meta.xml
<CustomField>
    <fullName>Vendor_UOM__c</fullName>
    <label>Vendor Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_of_Measure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PurchaseOrderLineTriggerTest.cls
@IsTest
private class PurchaseOrderLineTriggerTest {

    @IsTest
    static void testDefaultsAndCalculationsFromSourcingOption() {
        Business_Unit__c bu = ProcurementTestDataFactory.createBusinessUnit();
        Account vendor      = ProcurementTestDataFactory.createVendorAccount();
        Product2 product    = ProcurementTestDataFactory.createProduct();
        ProcurementTestDataFactory.createDefaultProductUom(product);

        Vendor_Product__c vp = ProcurementTestDataFactory.createVendorProduct(
            vendor, product, false
        );

        Product_Sourcing_Option__c pso = ProcurementTestDataFactory.createProductSourcingOption(
            bu, product, vendor, vp, false
        );

        Purchase_Order__c po = ProcurementTestDataFactory.createPurchaseOrder(bu, vendor);

        Test.startTest();
        Purchase_Order_Line__c line = new Purchase_Order_Line__c(
            Purchase_Order__c          = po.Id,
            Product_Sourcing_Option__c = pso.Id,
            Vendor_Quantity__c         = 10
            // Cost_Per_Vendor_Unit__c left null to be defaulted
        );
        insert line;
        Test.stopTest();

        line = [
            SELECT Id,
                   Product__c,
                   Vendor__c,
                   Vendor_Product__c,
                   Vendor_Quantity__c,
                   Vendor_UOM__c,
                   Conversion_Factor__c,
                   Internal_UOM__c,
                   Internal_Quantity__c,
                   Converted_Internal_Quantity__c,
                   Cost_Per_Vendor_Unit__c
            FROM Purchase_Order_Line__c
            WHERE Id = :line.Id
        ];

        System.assertEquals(product.Id, line.Product__c, 'Product should default from PSO / Vendor_Product.');
        System.assertEquals(vendor.Id,  line.Vendor__c,  'Vendor should default from PSO / Vendor_Product.');
        System.assertEquals(vp.Id,      line.Vendor_Product__c, 'Vendor_Product__c should default from PSO.');
        System.assertEquals('each',       line.Vendor_UOM__c, 'Vendor UOM should default from Vendor_Product.');
        System.assertEquals(1,          line.Conversion_Factor__c, 'Conversion factor should default from Vendor_Product.');
        System.assertEquals('each',       line.Internal_UOM__c, 'Internal UOM should default from Product_UOM.');

        System.assertEquals(10, line.Vendor_Quantity__c, 'Vendor qty should match input.');
        System.assertEquals(10, line.Converted_Internal_Quantity__c, 'Converted internal qty should be vendorQty * conversionFactor.');
        System.assertEquals(10, line.Internal_Quantity__c, 'Internal qty should default to converted internal qty.');

        System.assertEquals(
            vp.Base_Cost_Per_Vendor_Unit__c,
            line.Cost_Per_Vendor_Unit__c,
            'Cost per vendor unit should default from Vendor_Product when no contract cost in range.'
        );
    }

    @IsTest
    static void testBaseCostUsedWhenContractOutOfRange() {
        Business_Unit__c bu = ProcurementTestDataFactory.createBusinessUnit();
        Account vendor      = ProcurementTestDataFactory.createVendorAccount();
        Product2 product    = ProcurementTestDataFactory.createProduct();
        ProcurementTestDataFactory.createDefaultProductUom(product);

        Vendor_Product__c vp = ProcurementTestDataFactory.createVendorProduct(
            vendor, product, false
        );

        // Contract cost that is out of effective range (in the past)
        Product_Sourcing_Option__c pso = new Product_Sourcing_Option__c(
            Business_Unit__c                = bu.Id,
            Product__c                      = product.Id,
            Vendor__c                       = vendor.Id,
            Vendor_Product__c               = vp.Id,
            Contract_Cost_Per_Vendor_Unit__c = 5,
            Effective_From__c               = Date.today().addYears(-2),
            Effective_To__c                 = Date.today().addYears(-1),
            Is_Active__c                    = true
        );
        insert pso;

        Purchase_Order__c po = ProcurementTestDataFactory.createPurchaseOrder(bu, vendor);

        Test.startTest();
        Purchase_Order_Line__c line = new Purchase_Order_Line__c(
            Purchase_Order__c          = po.Id,
            Product_Sourcing_Option__c = pso.Id,
            Vendor_Quantity__c         = 3
        );
        insert line;
        Test.stopTest();

        line = [
            SELECT Cost_Per_Vendor_Unit__c
            FROM Purchase_Order_Line__c
            WHERE Id = :line.Id
        ];

        System.assertEquals(
            vp.Base_Cost_Per_Vendor_Unit__c,
            line.Cost_Per_Vendor_Unit__c,
            'When contract cost is out of range, base cost from Vendor_Product should be used.'
        );
    }

    @IsTest
    static void testRollupsAndStatusFromLines() {
        Business_Unit__c bu = ProcurementTestDataFactory.createBusinessUnit();
        Account vendor      = ProcurementTestDataFactory.createVendorAccount();
        Product2 product    = ProcurementTestDataFactory.createProduct();
        ProcurementTestDataFactory.createDefaultProductUom(product);

        Vendor_Product__c vp = ProcurementTestDataFactory.createVendorProduct(
            vendor, product, false
        );

        Product_Sourcing_Option__c pso = ProcurementTestDataFactory.createProductSourcingOption(
            bu, product, vendor, vp, false
        );

        Purchase_Order__c po = ProcurementTestDataFactory.createPurchaseOrder(bu, vendor);

        // Line 1: ordered, not received
        Purchase_Order_Line__c line1 = new Purchase_Order_Line__c(
            Purchase_Order__c          = po.Id,
            Product_Sourcing_Option__c = pso.Id,
            Vendor_Quantity__c         = 2,
            Cost_Per_Vendor_Unit__c    = 10,
            Status__c                  = 'Ordered'
        );

        // Line 2: fully received
        Purchase_Order_Line__c line2 = new Purchase_Order_Line__c(
            Purchase_Order__c          = po.Id,
            Product_Sourcing_Option__c = pso.Id,
            Vendor_Quantity__c         = 3,
            Cost_Per_Vendor_Unit__c    = 10,
            Status__c                  = 'Received',
            Received_Quantity_Internal__c = 3
        );

        Test.startTest();
        insert new List<Purchase_Order_Line__c>{ line1, line2 };
        Test.stopTest();

        po = [
            SELECT Id,
                   Subtotal__c,
                   Total_Internal_Quantity__c,
                   Received_Internal_Quantity__c,
                   Status__c
            FROM Purchase_Order__c
            WHERE Id = :po.Id
        ];

        System.assertEquals(50, po.Subtotal__c, 'Subtotal should be sum of line totals (2*10 + 3*10).');
        System.assertEquals(5,  po.Total_Internal_Quantity__c, 'Total internal qty should sum internal quantities (assuming factor 1).');
        System.assertEquals(3,  po.Received_Internal_Quantity__c, 'Received internal qty should sum received quantities.');

        System.assertEquals('Partially_Received', po.Status__c, 'Mixed ordered and received should yield Partially_Received.');
    }

    @IsTest
    static void testPurchaseOrderValidation_preventsBuChangeAndDeleteWithLines() {
        Business_Unit__c bu1 = ProcurementTestDataFactory.createBusinessUnit();
        Business_Unit__c bu2 = ProcurementTestDataFactory.createBusinessUnit();
        Account vendor       = ProcurementTestDataFactory.createVendorAccount();
        Product2 product     = ProcurementTestDataFactory.createProduct();
        ProcurementTestDataFactory.createDefaultProductUom(product);

        Vendor_Product__c vp = ProcurementTestDataFactory.createVendorProduct(
            vendor, product, false
        );

        Product_Sourcing_Option__c pso = ProcurementTestDataFactory.createProductSourcingOption(
            bu1, product, vendor, vp, false
        );

        Purchase_Order__c po = ProcurementTestDataFactory.createPurchaseOrder(bu1, vendor);

        Purchase_Order_Line__c line = new Purchase_Order_Line__c(
            Purchase_Order__c          = po.Id,
            Product_Sourcing_Option__c = pso.Id,
            Vendor_Quantity__c         = 1,
            Cost_Per_Vendor_Unit__c    = 10,
            Status__c                  = 'Ordered'
        );
        insert line;

        Test.startTest();

        // --- Try changing BU – should fail ---
        po.Business_Unit__c = bu2.Id;
        try {
            update po;
            System.assert(false, 'Expected error when changing BU on PO with lines.');
        } catch (DmlException e) {
            System.assert(
                e.getDmlMessage(0).contains('Cannot change Business Unit on a Purchase Order that has line items'),
                'Unexpected error when changing BU: ' + e.getDmlMessage(0)
            );
        }

        // Reload PO to ensure it still exists and BU is unchanged before delete test
        po = [
            SELECT Id, Business_Unit__c
            FROM Purchase_Order__c
            WHERE Id = :po.Id
        ];

        // --- Try deleting PO – should fail ---
        try {
            delete po;
            System.assert(false, 'Expected error when deleting PO with lines.');
        } catch (DmlException e) {
            System.assert(
                e.getDmlMessage(0).contains('Cannot delete a Purchase Order that has line items'),
                'Unexpected error when deleting PO: ' + e.getDmlMessage(0)
            );
        }

        Test.stopTest();
    }

}