force-app/main/default/objects/Product_Sourcing_Option__c/Product_Sourcing_Option__c.object-meta.xml
<CustomObject>
        <label>Product Sourcing Option</label>
    <nameField>
        <label>Sourcing Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sourcing Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Sourcing Option</relationshipLabel>
    <relationshipName>Product_Product_Sourcing_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Vendor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Sourcing Option</relationshipLabel>
    <relationshipName>Vendor_Product_Sourcing_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sourcing_Option__c/fields/Vendor_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor Product available to this Business Unit.</description>
    <label>Vendor Product</label>
    <referenceTo>Vendor_Product__c</referenceTo>
    <relationshipLabel>Product Sourcing Option</relationshipLabel>
    <relationshipName>Vendor_Products_Product_Sourcing_Option</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/Vendor_Product__c.object-meta.xml
<CustomObject>
    <label>Vendor Product</label>
    <nameField>
        <label>Vendor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Vendor Products</relationshipLabel>
    <relationshipName>Product_Vendor_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Product__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Vendor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Products</relationshipLabel>
    <relationshipName>Vendor_Vendor_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductSourcingOptionTriggerHandler.cls
// ============================================================================
// ProductSourcingOptionTriggerHandler
// - BEFORE INSERT/UPDATE:
//     * applyDefaults: fill in Vendor__c, Product__c, MOQ from Vendor_Product__c
//       if Vendor_Product__c is set and those fields are blank.
//     * validate: enforce uniqueness of PSO per (BU, Vendor_Product) and
//       single default PSO per (BU, Product).
// - AFTER: reserved for future behaviors (e.g., logging/audits).
// ============================================================================
public with sharing class ProductSourcingOptionTriggerHandler {

    public static void run() {
        if (Trigger.isBefore) {
            handleBefore(Trigger.operationType, Trigger.new, Trigger.old);
        }
        if (Trigger.isAfter) {
            handleAfter(Trigger.operationType, Trigger.new, Trigger.old);
        }
    }

    private static void handleBefore(
        System.TriggerOperation operationType,
        List<Product_Sourcing_Option__c> newList,
        List<Product_Sourcing_Option__c> oldList
    ) {
        switch on operationType {
            when BEFORE_INSERT {
                ProductSourcingOptionDefaultsService.applyDefaults(newList);
                ProductSourcingOptionValidationService.validate(newList);
            }
            when BEFORE_UPDATE {
                ProductSourcingOptionDefaultsService.applyDefaults(newList, oldList);
                ProductSourcingOptionValidationService.validate(newList, oldList);
            }
            when BEFORE_DELETE {
                // If you want "in use" checks later (e.g. PSO on existing POs),
                // they can go in a dedicated DeleteValidationService.
            }
            when else {
                // no-op
            }
        }
    }

    private static void handleAfter(
        System.TriggerOperation operationType,
        List<Product_Sourcing_Option__c> newList,
        List<Product_Sourcing_Option__c> oldList
    ) {
        switch on operationType {
            when AFTER_INSERT {
                // Future extension point (e.g., logging, integration hooks).
            }
            when AFTER_UPDATE {
                // Future extension point.
            }
            when AFTER_DELETE {
                // Future extension point.
            }
            when AFTER_UNDELETE {
                // Future extension point.
            }
            when else {
                // no-op
            }
        }
    }
}